export type Signal = "bullish" | "bearish" | "neutral";
export type Level = 1 | 2 | 3 | 4;

export interface CandlePattern {
  id: number;
  name: string;
  level: Level;
  levelName: string;
  signal: Signal;
  candles: number;
  description: string;
  whatItSignals: string;
  reliability: "High" | "Medium" | "Low";
  svgPath: string;
}

export const CANDLESTICK_PATTERNS: CandlePattern[] = [
  // ============================================
  // LEVEL 1 — Beginner (Single-candle patterns)
  // ============================================
  {
    id: 1,
    name: "Doji",
    level: 1,
    levelName: "Beginner",
    signal: "neutral",
    candles: 1,
    description: "Tiny or no body, wicks on both sides roughly equal. Shows indecision between buyers and sellers.",
    whatItSignals: "Market indecision — buyers and sellers are balanced. Wait for confirmation.",
    reliability: "Medium",
    svgPath: "M25,10 L25,40 M15,25 L35,25",
  },
  {
    id: 2,
    name: "Long-Legged Doji",
    level: 1,
    levelName: "Beginner",
    signal: "neutral",
    candles: 1,
    description: "Doji with very long wicks on both sides. High volatility during the period.",
    whatItSignals: "Strong indecision with high volatility. Big moves possible next.",
    reliability: "Medium",
    svgPath: "M25,5 L25,45 M10,25 L40,25",
  },
  {
    id: 3,
    name: "Dragonfly Doji",
    level: 1,
    levelName: "Beginner",
    signal: "bullish",
    candles: 1,
    description: "Flat top, long lower wick, no upper wick. Price dropped but recovered.",
    whatItSignals: "Bullish reversal — sellers pushed down but buyers brought it back up.",
    reliability: "High",
    svgPath: "M25,15 L25,45 M15,15 L35,15",
  },
  {
    id: 4,
    name: "Gravestone Doji",
    level: 1,
    levelName: "Beginner",
    signal: "bearish",
    candles: 1,
    description: "Flat bottom, long upper wick, no lower wick. Price rose but fell back.",
    whatItSignals: "Bearish reversal — buyers pushed up but sellers brought it back down.",
    reliability: "High",
    svgPath: "M25,5 L25,35 M15,35 L35,35",
  },
  {
    id: 5,
    name: "Hammer",
    level: 1,
    levelName: "Beginner",
    signal: "bullish",
    candles: 1,
    description: "Small body near top, long lower wick (2x+ body size). Looks like a hammer.",
    whatItSignals: "Bullish reversal — after a downtrend, buyers are stepping in.",
    reliability: "High",
    svgPath: "M25,10 L30,10 L30,18 L25,18 Z M27.5,18 L27.5,42",
  },
  {
    id: 6,
    name: "Inverted Hammer",
    level: 1,
    levelName: "Beginner",
    signal: "bullish",
    candles: 1,
    description: "Small body near bottom, long upper wick. Price tried to go up.",
    whatItSignals: "Possible bullish reversal — buying pressure starting to appear.",
    reliability: "Medium",
    svgPath: "M25,32 L30,32 L30,40 L25,40 Z M27.5,8 L27.5,32",
  },
  {
    id: 7,
    name: "Hanging Man",
    level: 1,
    levelName: "Beginner",
    signal: "bearish",
    candles: 1,
    description: "Same shape as Hammer, but appears after an uptrend. Warning sign.",
    whatItSignals: "Bearish warning — after an uptrend, selling pressure is building.",
    reliability: "Medium",
    svgPath: "M25,10 L30,10 L30,18 L25,18 Z M27.5,18 L27.5,42",
  },
  {
    id: 8,
    name: "Shooting Star",
    level: 1,
    levelName: "Beginner",
    signal: "bearish",
    candles: 1,
    description: "Small body near bottom, long upper wick. Price rose then fell hard.",
    whatItSignals: "Bearish reversal — after an uptrend, sellers are taking control.",
    reliability: "High",
    svgPath: "M25,32 L30,32 L30,40 L25,40 Z M27.5,8 L27.5,32",
  },
  {
    id: 9,
    name: "Bullish Marubozu",
    level: 1,
    levelName: "Beginner",
    signal: "bullish",
    candles: 1,
    description: "Full green body with no wicks. Price opened low and closed high, never went lower.",
    whatItSignals: "Strong buying pressure — bulls controlled the entire period.",
    reliability: "High",
    svgPath: "M18,10 L32,10 L32,40 L18,40 Z",
  },
  {
    id: 10,
    name: "Bearish Marubozu",
    level: 1,
    levelName: "Beginner",
    signal: "bearish",
    candles: 1,
    description: "Full red body with no wicks. Price opened high and closed low, never went higher.",
    whatItSignals: "Strong selling pressure — bears controlled the entire period.",
    reliability: "High",
    svgPath: "M18,10 L32,10 L32,40 L18,40 Z",
  },
  {
    id: 11,
    name: "Spinning Top",
    level: 1,
    levelName: "Beginner",
    signal: "neutral",
    candles: 1,
    description: "Small body centered between small wicks. Neither buyers nor sellers won.",
    whatItSignals: "Weak momentum — market is undecided. Wait for next candle.",
    reliability: "Low",
    svgPath: "M22,20 L28,20 L28,30 L22,30 Z M25,10 L25,20 M25,30 L25,40",
  },

  // ============================================
  // LEVEL 2 — Intermediate (Two-candle patterns)
  // ============================================
  {
    id: 12,
    name: "Bullish Engulfing",
    level: 2,
    levelName: "Intermediate",
    signal: "bullish",
    candles: 2,
    description: "Small red candle, then a bigger green candle that fully covers it.",
    whatItSignals: "Strong bullish reversal — buyers overwhelmed sellers completely.",
    reliability: "High",
    svgPath: "M8,20 L16,20 L16,30 L8,30 Z M18,10 L38,10 L38,40 L18,40 Z",
  },
  {
    id: 13,
    name: "Bearish Engulfing",
    level: 2,
    levelName: "Intermediate",
    signal: "bearish",
    candles: 2,
    description: "Small green candle, then a bigger red candle that fully covers it.",
    whatItSignals: "Strong bearish reversal — sellers overwhelmed buyers completely.",
    reliability: "High",
    svgPath: "M8,20 L16,20 L16,30 L8,30 Z M18,10 L38,10 L38,40 L18,40 Z",
  },
  {
    id: 14,
    name: "Piercing Line",
    level: 2,
    levelName: "Intermediate",
    signal: "bullish",
    candles: 2,
    description: "Red candle, then green candle opening below its low but closing above its midpoint.",
    whatItSignals: "Bullish reversal — buyers pushed price back above the midpoint.",
    reliability: "Medium",
    svgPath: "M8,15 L18,15 L18,35 L8,35 Z M20,38 L38,38 L38,20 L20,20 Z",
  },
  {
    id: 15,
    name: "Dark Cloud Cover",
    level: 2,
    levelName: "Intermediate",
    signal: "bearish",
    candles: 2,
    description: "Green candle, then red candle opening above its high but closing below its midpoint.",
    whatItSignals: "Bearish reversal — sellers pushed price back below the midpoint.",
    reliability: "Medium",
    svgPath: "M8,20 L18,20 L18,35 L8,35 Z M20,8 L38,8 L38,25 L20,25 Z",
  },
  {
    id: 16,
    name: "Bullish Harami",
    level: 2,
    levelName: "Intermediate",
    signal: "bullish",
    candles: 2,
    description: "Large red candle, then a small green candle contained inside its body.",
    whatItSignals: "Possible bullish reversal — selling momentum is fading.",
    reliability: "Medium",
    svgPath: "M8,10 L22,10 L22,40 L8,40 Z M24,20 L34,20 L34,30 L24,30 Z",
  },
  {
    id: 17,
    name: "Bearish Harami",
    level: 2,
    levelName: "Intermediate",
    signal: "bearish",
    candles: 2,
    description: "Large green candle, then a small red candle contained inside its body.",
    whatItSignals: "Possible bearish reversal — buying momentum is fading.",
    reliability: "Medium",
    svgPath: "M8,10 L22,10 L22,40 L8,40 Z M24,20 L34,20 L34,30 L24,30 Z",
  },
  {
    id: 18,
    name: "Tweezer Bottom",
    level: 2,
    levelName: "Intermediate",
    signal: "bullish",
    candles: 2,
    description: "Two candles with matching or near-matching lows. Support forming.",
    whatItSignals: "Bullish reversal — price found support at this level.",
    reliability: "Medium",
    svgPath: "M8,15 L16,15 L16,40 L8,40 Z M24,20 L32,20 L32,40 L24,40 Z",
  },
  {
    id: 19,
    name: "Tweezer Top",
    level: 2,
    levelName: "Intermediate",
    signal: "bearish",
    candles: 2,
    description: "Two candles with matching or near-matching highs. Resistance forming.",
    whatItSignals: "Bearish reversal — price found resistance at this level.",
    reliability: "Medium",
    svgPath: "M8,10 L16,10 L16,35 L8,35 Z M24,10 L32,10 L32,30 L24,30 Z",
  },
  {
    id: 20,
    name: "Bullish Kicker",
    level: 2,
    levelName: "Intermediate",
    signal: "bullish",
    candles: 2,
    description: "Red candle, then a green candle that gaps up and doesn't overlap.",
    whatItSignals: "Very strong bullish reversal — sudden shift in sentiment.",
    reliability: "High",
    svgPath: "M8,20 L16,20 L16,35 L8,35 Z M24,5 L38,5 L38,18 L24,18 Z",
  },
  {
    id: 21,
    name: "Bearish Kicker",
    level: 2,
    levelName: "Intermediate",
    signal: "bearish",
    candles: 2,
    description: "Green candle, then a red candle that gaps down and doesn't overlap.",
    whatItSignals: "Very strong bearish reversal — sudden shift in sentiment.",
    reliability: "High",
    svgPath: "M8,15 L16,15 L16,30 L8,30 Z M24,35 L38,35 L38,48 L24,48 Z",
  },

  // ============================================
  // LEVEL 3 — Advanced (Three+ candle patterns)
  // ============================================
  {
    id: 22,
    name: "Morning Star",
    level: 3,
    levelName: "Advanced",
    signal: "bullish",
    candles: 3,
    description: "Red candle → small-body candle (gap down) → green candle closing into candle 1.",
    whatItSignals: "Strong bullish reversal — bottom forming after downtrend.",
    reliability: "High",
    svgPath: "M5,15 L13,15 L13,35 L5,35 Z M17,30 L23,30 L23,36 L17,36 Z M27,38 L40,38 L40,18 L27,18 Z",
  },
  {
    id: 23,
    name: "Evening Star",
    level: 3,
    levelName: "Advanced",
    signal: "bearish",
    candles: 3,
    description: "Green candle → small-body candle (gap up) → red candle closing into candle 1.",
    whatItSignals: "Strong bearish reversal — top forming after uptrend.",
    reliability: "High",
    svgPath: "M5,20 L13,20 L13,38 L5,38 Z M17,14 L23,14 L23,20 L17,20 Z M27,12 L40,12 L40,32 L27,32 Z",
  },
  {
    id: 24,
    name: "Morning Doji Star",
    level: 3,
    levelName: "Advanced",
    signal: "bullish",
    candles: 3,
    description: "Same as Morning Star, but middle candle is a Doji.",
    whatItSignals: "Very strong bullish reversal — indecision at the bottom.",
    reliability: "High",
    svgPath: "M5,15 L13,15 L13,35 L5,35 Z M19,30 L19,36 M15,33 L23,33 M27,38 L40,38 L40,18 L27,18 Z",
  },
  {
    id: 25,
    name: "Evening Doji Star",
    level: 3,
    levelName: "Advanced",
    signal: "bearish",
    candles: 3,
    description: "Same as Evening Star, but middle candle is a Doji.",
    whatItSignals: "Very strong bearish reversal — indecision at the top.",
    reliability: "High",
    svgPath: "M5,20 L13,20 L13,38 L5,38 Z M19,14 L19,20 M15,17 L23,17 M27,12 L40,12 L40,32 L27,32 Z",
  },
  {
    id: 26,
    name: "Three White Soldiers",
    level: 3,
    levelName: "Advanced",
    signal: "bullish",
    candles: 3,
    description: "Three consecutive green candles, each opening within the last and closing higher.",
    whatItSignals: "Strong bullish trend confirmation — sustained buying pressure.",
    reliability: "High",
    svgPath: "M5,28 L12,28 L12,38 L5,38 Z M15,22 L22,22 L22,32 L15,32 Z M25,14 L32,14 L32,24 L25,24 Z",
  },
  {
    id: 27,
    name: "Three Black Crows",
    level: 3,
    levelName: "Advanced",
    signal: "bearish",
    candles: 3,
    description: "Three consecutive red candles, each opening within the last and closing lower.",
    whatItSignals: "Strong bearish trend confirmation — sustained selling pressure.",
    reliability: "High",
    svgPath: "M5,14 L12,14 L12,24 L5,24 Z M15,20 L22,20 L22,30 L15,30 Z M25,28 L32,28 L32,38 L25,38 Z",
  },
  {
    id: 28,
    name: "Three Inside Up",
    level: 3,
    levelName: "Advanced",
    signal: "bullish",
    candles: 3,
    description: "Bullish Harami followed by a third green candle breaking above candle 1's high.",
    whatItSignals: "Confirmed bullish reversal — Harami pattern validated.",
    reliability: "High",
    svgPath: "M5,12 L15,12 L15,38 L5,38 Z M17,22 L25,22 L25,30 L17,30 Z M27,20 L38,20 L38,8 L27,8 Z",
  },
  {
    id: 29,
    name: "Three Inside Down",
    level: 3,
    levelName: "Advanced",
    signal: "bearish",
    candles: 3,
    description: "Bearish Harami followed by a third red candle breaking below candle 1's low.",
    whatItSignals: "Confirmed bearish reversal — Harami pattern validated.",
    reliability: "High",
    svgPath: "M5,12 L15,12 L15,38 L5,38 Z M17,22 L25,22 L25,30 L17,30 Z M27,32 L38,32 L38,44 L27,44 Z",
  },
  {
    id: 30,
    name: "Three Outside Up",
    level: 3,
    levelName: "Advanced",
    signal: "bullish",
    candles: 3,
    description: "Bullish Engulfing followed by a third green candle closing higher.",
    whatItSignals: "Confirmed bullish reversal — Engulfing pattern validated.",
    reliability: "High",
    svgPath: "M5,22 L13,22 L13,32 L5,32 Z M15,10 L30,10 L30,38 L15,38 Z M32,8 L42,8 L42,22 L32,22 Z",
  },
  {
    id: 31,
    name: "Three Outside Down",
    level: 3,
    levelName: "Advanced",
    signal: "bearish",
    candles: 3,
    description: "Bearish Engulfing followed by a third red candle closing lower.",
    whatItSignals: "Confirmed bearish reversal — Engulfing pattern validated.",
    reliability: "High",
    svgPath: "M5,22 L13,22 L13,32 L5,32 Z M15,10 L30,10 L30,38 L15,38 Z M32,28 L42,28 L42,44 L32,44 Z",
  },
  {
    id: 32,
    name: "Rising Three Methods",
    level: 3,
    levelName: "Advanced",
    signal: "bullish",
    candles: 5,
    description: "Big green candle, 3 small red candles inside its range, then another big green.",
    whatItSignals: "Bullish continuation — brief pause in uptrend, then resume.",
    reliability: "Medium",
    svgPath: "M3,10 L10,10 L10,38 L3,38 Z M13,18 L17,18 L17,28 L13,28 Z M19,16 L23,16 L23,26 L19,26 Z M25,18 L29,18 L29,28 L25,28 Z M32,10 L42,10 L42,38 L32,38 Z",
  },
  {
    id: 33,
    name: "Falling Three Methods",
    level: 3,
    levelName: "Advanced",
    signal: "bearish",
    candles: 5,
    description: "Big red candle, 3 small green candles inside its range, then another big red.",
    whatItSignals: "Bearish continuation — brief pause in downtrend, then resume.",
    reliability: "Medium",
    svgPath: "M3,10 L10,10 L10,38 L3,38 Z M13,18 L17,18 L17,28 L13,28 Z M19,16 L23,16 L23,26 L19,26 Z M25,18 L29,18 L29,28 L25,28 Z M32,10 L42,10 L42,38 L32,38 Z",
  },
  {
    id: 34,
    name: "Bullish Abandoned Baby",
    level: 3,
    levelName: "Advanced",
    signal: "bullish",
    candles: 3,
    description: "Red candle → Doji that gaps below both neighbors → green candle gapping back up.",
    whatItSignals: "Rare, very strong bullish reversal — complete sentiment shift.",
    reliability: "High",
    svgPath: "M5,15 L12,15 L12,30 L5,30 Z M17,36 L17,42 M13,39 L21,39 M26,34 L38,34 L38,14 L26,14 Z",
  },
  {
    id: 35,
    name: "Bearish Abandoned Baby",
    level: 3,
    levelName: "Advanced",
    signal: "bearish",
    candles: 3,
    description: "Green candle → Doji that gaps above both neighbors → red candle gapping back down.",
    whatItSignals: "Rare, very strong bearish reversal — complete sentiment shift.",
    reliability: "High",
    svgPath: "M5,20 L12,20 L12,35 L5,35 Z M17,8 L17,14 M13,11 L21,11 M26,18 L38,18 L38,38 L26,38 Z",
  },

  // ============================================
  // LEVEL 4 — Pro chart structures (multi-candle)
  // ============================================
  {
    id: 36,
    name: "Double Top",
    level: 4,
    levelName: "Pro",
    signal: "bearish",
    candles: 10,
    description: "Price hits a high twice, fails to break through, dips between the two peaks.",
    whatItSignals: "Bearish reversal — strong resistance level confirmed.",
    reliability: "High",
    svgPath: "M5,35 L10,15 L15,25 L20,12 L25,25 L30,15 L35,30 L40,40",
  },
  {
    id: 37,
    name: "Double Bottom",
    level: 4,
    levelName: "Pro",
    signal: "bullish",
    candles: 10,
    description: "Price hits a low twice, fails to break lower, bounces between the two troughs.",
    whatItSignals: "Bullish reversal — strong support level confirmed.",
    reliability: "High",
    svgPath: "M5,10 L10,35 L15,25 L20,38 L25,25 L30,35 L35,20 L40,10",
  },
  {
    id: 38,
    name: "Head and Shoulders",
    level: 4,
    levelName: "Pro",
    signal: "bearish",
    candles: 15,
    description: "Three peaks — middle one highest (head), two lower ones (shoulders).",
    whatItSignals: "Bearish reversal — trend exhaustion and reversal likely.",
    reliability: "High",
    svgPath: "M3,30 L8,18 L13,28 L18,8 L23,28 L28,16 L33,30 L40,40",
  },
  {
    id: 39,
    name: "Inverse Head & Shoulders",
    level: 4,
    levelName: "Pro",
    signal: "bullish",
    candles: 15,
    description: "Three troughs — middle one lowest, two higher ones (inverse of H&S).",
    whatItSignals: "Bullish reversal — downtrend exhaustion and reversal likely.",
    reliability: "High",
    svgPath: "M3,15 L8,32 L13,22 L18,42 L23,22 L28,34 L33,20 L40,10",
  },
  {
    id: 40,
    name: "Ascending Triangle",
    level: 4,
    levelName: "Pro",
    signal: "bullish",
    candles: 12,
    description: "Flat resistance on top, rising support line underneath. Price squeezing up.",
    whatItSignals: "Usually bullish breakout — buyers getting more aggressive.",
    reliability: "Medium",
    svgPath: "M5,35 L12,28 L18,30 L25,22 L30,24 L38,15 M5,15 L40,15",
  },
  {
    id: 41,
    name: "Descending Triangle",
    level: 4,
    levelName: "Pro",
    signal: "bearish",
    candles: 12,
    description: "Flat support on bottom, falling resistance line above. Price squeezing down.",
    whatItSignals: "Usually bearish breakdown — sellers getting more aggressive.",
    reliability: "Medium",
    svgPath: "M5,15 L12,22 L18,20 L25,28 L30,26 L38,35 M5,35 L40,35",
  },
  {
    id: 42,
    name: "Symmetrical Triangle",
    level: 4,
    levelName: "Pro",
    signal: "neutral",
    candles: 12,
    description: "Both trendlines converging — support rising, resistance falling. Squeezing.",
    whatItSignals: "Breakout direction unclear — wait for the breakout to confirm.",
    reliability: "Low",
    svgPath: "M5,35 L12,28 L18,25 L25,22 L30,20 L38,15 M5,15 L12,22 L18,25 L25,28 L30,30 L38,35",
  },
  {
    id: 43,
    name: "Bull Flag",
    level: 4,
    levelName: "Pro",
    signal: "bullish",
    candles: 10,
    description: "Sharp rise (flagpole), then a small downward-sloping consolidation channel.",
    whatItSignals: "Bullish continuation — brief pause before next leg up.",
    reliability: "High",
    svgPath: "M5,40 L12,10 L15,15 L20,12 L25,18 L30,15 L35,20 L38,18",
  },
  {
    id: 44,
    name: "Bear Flag",
    level: 4,
    levelName: "Pro",
    signal: "bearish",
    candles: 10,
    description: "Sharp drop (flagpole), then a small upward-sloping consolidation channel.",
    whatItSignals: "Bearish continuation — brief pause before next leg down.",
    reliability: "High",
    svgPath: "M5,10 L12,40 L15,35 L20,38 L25,32 L30,35 L35,30 L38,32",
  },
  {
    id: 45,
    name: "Cup and Handle",
    level: 4,
    levelName: "Pro",
    signal: "bullish",
    candles: 20,
    description: "Rounded 'U' shaped dip and recovery, then a small pullback ('handle').",
    whatItSignals: "Bullish continuation/breakout — accumulation phase complete.",
    reliability: "High",
    svgPath: "M5,15 L10,30 L15,38 L20,40 L25,38 L30,30 L35,18 L38,22 L42,20",
  },
  {
    id: 46,
    name: "Rising Wedge",
    level: 4,
    levelName: "Pro",
    signal: "bearish",
    candles: 12,
    description: "Both trendlines rising but converging — narrowing range upward.",
    whatItSignals: "Usually bearish reversal — momentum fading as price rises.",
    reliability: "Medium",
    svgPath: "M5,38 L12,30 L18,26 L25,22 L30,18 L38,12 M5,32 L12,28 L18,24 L25,20 L30,16 L38,10",
  },
  {
    id: 47,
    name: "Falling Wedge",
    level: 4,
    levelName: "Pro",
    signal: "bullish",
    candles: 12,
    description: "Both trendlines falling but converging — narrowing range downward.",
    whatItSignals: "Usually bullish reversal — selling pressure fading as price drops.",
    reliability: "Medium",
    svgPath: "M5,12 L12,20 L18,24 L25,28 L30,32 L38,38 M5,18 L12,22 L18,26 L25,30 L30,34 L38,40",
  },
];

export function getPatternsByLevel(level: Level): CandlePattern[] {
  return CANDLESTICK_PATTERNS.filter((p) => p.level === level);
}

export function getPatternsBySignal(signal: Signal): CandlePattern[] {
  return CANDLESTICK_PATTERNS.filter((p) => p.signal === signal);
}

export function getPatternById(id: number): CandlePattern | undefined {
  return CANDLESTICK_PATTERNS.find((p) => p.id === id);
}

export const LEVEL_INFO = [
  { level: 1 as Level, name: "Beginner", description: "Single-candle patterns — easiest to spot", count: 11 },
  { level: 2 as Level, name: "Intermediate", description: "Two-candle patterns — compare consecutive candles", count: 10 },
  { level: 3 as Level, name: "Advanced", description: "Three+ candle patterns — read short sequences", count: 14 },
  { level: 4 as Level, name: "Pro", description: "Chart structures — shapes across many candles", count: 12 },
];
