export { default as Navbar } from "./Navbar";
export { default as Hero } from "./Hero";
export { default as StatsBar } from "./StatsBar";
export { default as Features } from "./Features";
export { default as HowToStart } from "./HowToStart";
export { default as Payouts } from "./Payouts";
export { default as Security } from "./Security";
export { default as FAQ } from "./FAQ";
export { default as Footer } from "./Footer";
