import os
from dotenv import load_dotenv

load_dotenv()

SYMBOLS = [
    "BTCUSDT", "ETHUSDT", "SOLUSDT", "BNBUSDT", "XRPUSDT",
    "DOGEUSDT", "ADAUSDT", "AVAXUSDT", "LINKUSDT", "DOTUSDT",
    "MATICUSDT", "UNIUSDT", "LTCUSDT", "ATOMUSDT", "NEARUSDT",
    "APTUSDT", "ARBUSDT", "OPUSDT", "SUIUSDT", "INJUSDT",
    "FILUSDT", "RENDERUSDT", "SEIUSDT", "TIAUSDT", "WLDUSDT",
]

BINANCE_FUTURES_BASE = "https://fapi.binance.com"
TIMEFRAMES = ["15m", "1h", "4h"]
KLINES_LIMIT = 100
REFRESH_INTERVAL = 60

SCORE_STRONG = 65
SCORE_MEDIUM = 45
SCORE_WAIT = 25

MAX_CONCURRENT = 10
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
